### PR TITLE
redirect to notebook and scroll to paragraph from search view

### PR DESCRIPTION
**Pull request by heruka-urgyen**
- [x] scroll to particular paragraph when coming to a notebook from search
- [x] clear search field when navigating to home view `(/)`

### CODE REVIEW

**Comment by bzz** [comment]
Great! Can you please make sure that `./grunt jshint:all` passes on this one?

Another thing to check is that web ui runs from zeppelin after `mvn clean package -DskipTests`  + `./bin/zeppelin-daemon.sh start`

**Comment by heruka-urgyen** [comment]
If I start contributing to zeppelin actively, those jshint rules will go to hell, because I cannot work like this )

**Comment by heruka-urgyen** [comment]
@bzz I amended and force-pushed previous commit with jshint changes

**Comment by bzz** [comment]
:+1: awesome

**Pull request merged**
