### PR TITLE
fix links to notebook from search results

### PR DESCRIPTION
**Pull request by heruka-urgyen**
links broke due to changes in paragraph id on backend

### CODE REVIEW

**Comment by bzz** [comment]
What if we get rid of hard-coded string matching here, and will split the id by `/` and use first and last part of the result?

**Comment by heruka-urgyen** [comment]
it's more cumbersome. do you expect middle part to change a lot? or otherwise, why do you suggest not to hardcode it?

**Comment by bzz** [comment]
Just a suggestion, because it's very easy to forget to change it in the second place.
I expect structure to be the same though (even if something in the middle changes)

**Comment by heruka-urgyen** [comment]
okay, let me follow your advice and reimplement it then

**Comment by bzz** [comment]
It's up to you, really. 
If you think current one is ok - we can keep that. I have fixed backend bug so it's `paragraph` again.

**Comment by heruka-urgyen** [comment]
Then let's close this one if things are back to normal. Search is far from done yet, so I'll have a chance to tackle this problem again later

**Comment by bzz** [comment]
Sounds good, thanks!

**Pull request closed without merging**
